Refactor set up check fail
everypolitician-scrapers/zambia-na-scraper pull request #10
Opened 2017-02-28 12:35 UTC by ondenman

This is a step towards scraping the 2016 term.

Part of: https://github.com/everypolitician/everypolitician-data/issues/26473

2017-02-28 14:25 UTC, tmtmtmtm requested changes
As well as the issue in-place, the PR title here is a little too much like word soup for my taste. (Made worse because don't need a 'Refactor' here: the script checks the branch name, not the PR title, as you know from changing that part of the script itself.)

The description is also a little misleading, or is at least hiding what you're actually doing.

2017-02-28 14:25 UTC, tmtmtmtm commented on .travis.yml
> +script:
You can't combine script tags like this. This ends up with:

```ruby
YAML.load_file('.travis.yml')
=> {"language"=>"ruby", "script"=>["bundle exec rake", "bin/check-fail.sh"], "rvm"=>["2.3.3"], "sudo"=>false, "cache"=>"bundler"}
```

i.e. losing the `rubocop` check.

2017-02-28 14:39 UTC, ondenman commented on .travis.yml
> +script:
I've removed the `rubocop` script entry in a fix up. Rubocop is part of the default Rake script so I assume I don't need to call it explicitly.

2017-03-01 12:34 UTC, tmtmtmtm approved these changes

2017-03-01 12:34 UTC, merged